= Portfolio

[NOTE]
====
Those routes will only be available if :

* at least one exchange has _balances_ feature enabled
* _coinmarketcap_ service is enabled

====

== Retrieve portfolio across all exchanges

*GET* _/portfolio_

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|exchanges
|string (comma-separated)
|
|Comma-separated list of exchanges to include in portfolio

|===

=== Result

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|price
|float
|Estimated price of portfolio in $

|balances
|object
|one entry per currency, currency symbol being the key

|_{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}currency_
|
|Information for currency _currency_

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}volume
|float
|Volume of current currency

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}price
|float
|Estimated price in $ for current currency

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}pricePercent
|float [0,100]
|% of portfolio (based on price) represented by current currency

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}unknownPrice
|boolean
|Whether or not price is unknown. Price will be unknown if such currency does not exist in Coin Market Cap

|===

.Examples

Example for *GET* _/portfolio_

[source,json]
----
{
    "balances":{
        "PINK":{
            "volume":1538.5109958399999,
            "price":0,
            "pricePercent":0,
            "unknownPrice":true
        },
        "ETH":{
            "volume":1.11208348,
            "price":1191.2416,
            "pricePercent":20.25,
            "unknownPrice":false
        },
        "BLK":{
            "volume":209.84192613,
            "price":0,
            "pricePercent":0,
            "unknownPrice":true
        },
        "BTC":{
            "volume":0.28314554999999997,
            "price":3380.9561,
            "pricePercent":57.49,
            "unknownPrice":false
        },
        "USDT":{
            "volume":1292.68608245,
            "price":1309.1808,
            "pricePercent":22.26,
            "unknownPrice":false
        },
        "KORE":{
            "volume":583.04778728,
            "price":0,
            "pricePercent":0,
            "unknownPrice":true
        },
        "XMY":{
            "volume":1390.18863437,
            "price":0,
            "pricePercent":0,
            "unknownPrice":true
        },
        "XMG":{
            "volume":759.00263044,
            "price":0,
            "pricePercent":0,
            "unknownPrice":true
        }
    },
    "price":5881.3785
}
----
