= Trades

== Retrieves last trades for a given pair

*GET* _/exchanges/poloniex/trades/{pair}_

Uses Poloniex _returnTradeHistory_ API

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{pair}
|string
|Pair to retrieve last trades for (_X-Y_)

|===

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|outputFormat
|string (_custom_,_exchange_)
|custom
|If value is _exchange_ result returned by remote exchange will be returned untouched

|afterTradeId
|integer
|
|Only retrieve trades with an _id_ > _afterTradeId_ (will be ignored if _outputFormat_ is set to _exchange_)

|===

[NOTE]
====
Poloniex only allows to retrieve a maximum of 200 trades at once
====

=== Result

[NOTE]
====
This only applies when _outputFormat_ is set to _custom_
====

Result will be an array of trade object (*the first one being the newest*)

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|id
|integer
|Unique identifier of the trade

|quantity
|float
|Quantity bougth/sold during the trade

|rate
|float
|Per-unit price

|price
|float
|Total price (_quantity_ * _rate_)

|orderType
|string (_buy_,_sell_)
|Whether market maker was _buyer_ or _seller_

|timestamp
|float (unix timestamp sec.msec)
|Unix timestamp when trade was executed

|===

.Examples

Example for *GET* _/exchanges/poloniex/trades/BTC-ETH_

[source,json]
----
[
    {
        "id":34385736,
        "quantity":0.10201331,
        "rate":0.07298892,
        "price":0.00744584,
        "orderType":"buy",
        "timestamp":1505722177.120
    },
    {
        "id":34385735,
        "quantity":0.6,
        "rate":0.0729037,
        "price":0.04374222,
        "orderType":"sell",
        "timestamp":1505722171.130
    },
    {
        "id":34385734,
        "quantity":0.02,
        "rate":0.0729926,
        "price":0.00145985,
        "orderType":"buy",
        "timestamp":1505722156.140
    }
]
----
