= Tickers

[NOTE]
====
Those routes require the feature _tickers_ to be enabled for the requested exchange

[source,json]
----
{
    "features":{
        "tickers":{
            "enabled":true
        }
    }
}
----

====

== Retrieve tickers for all pairs or a list of pairs

[NOTE]
====
Some exchange require to retrieve _tickers_ for each pair separately. This is indicated in feature _tickers_

[source,json]
----
{
    "features":{
        "tickers":{
            "enabled":true,
            "withoutPair":false,
            "requirePair":false
        }
    }
}
----

* When _withoutPair_ is _false_, it means exchange requires _tickers_ to be retrieved for each pair separately
* When _requirePair_ is _false_, it means _gateway_ will provide a fallback method to retrieve _tickers_ for all pairs by looping over all existing pairs
* When _requirePair_ is _true_, it means that client will not be able to retrieve _tickers_ for all pairs at the same time

====

*GET* _/exchanges/{exchangeId}/tickers_

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|pairs
|string (comma-separated)
|
|Comma-separated list of pairs to retrieve tickers for

|===

=== Result

Result will be a dictionary using pairs as keys

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|_pair_
|string
|Pair name _X-Y_

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}pair
|string
|Pair name _X-Y_ (same as _pair_ key)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}last
|float
|Last trade's price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}priceChangePercent
|float
|% Change of price in last 24H (0-100) (will be null if not supported by exchange)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}sell
|float
|Lowest sell price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}buy
|float
|Highest buy price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}high
|float
|Highest price (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}low
|float
|Lowest price (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}volume
|float
|Volume (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}timestamp
|float (unix timestamp sec.msec)
|Unix timestamp

|===

.Examples

Example for *GET* _/exchanges/bittrex/tickers_

[source,json]
----
{
    "BITCNY-BTC":{
        "pair":"BITCNY-BTC",
        "last":22510,
        "priceChangePercent":5.4,
        "sell":23392.04999994,
        "buy":22510,
        "high":23400,
        "low":22365.99400001,
        "volume":3.85275902,
        "timestamp":1502369663.120
    },
    "BTC-1ST":{
        "pair":"BTC-1ST",
        "last":0.00027,
        "priceChangePercent":-1.2,
        "sell":0.00027,
        "buy":0.00026844,
        "high":0.00030997,
        "low":0.000251,
        "volume":1209270.05703722,
        "timestamp":1502369448.130
    },
    ...
}
----

== Retrieve ticker for a single pair

*GET* _/exchanges/{exchangeId}/tickers/{pair}_

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{pair}
|string
|Pair to retrieve information for (_X-Y_)

|===

=== Result

Result will be a dictionary containing a single entry

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|_pair_
|string
|Pair name _X-Y_ as requested in {pair}

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}pair
|string
|Pair name _X-Y_ (same as _pair_ key)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}last
|float
|Last trade's price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}priceChangePercent
|float
|% Change of price in last 24H (0-100) (will be null if not supported by exchange)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}sell
|float
|Lowest sell price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}buy
|float
|Highest buy price

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}high
|float
|Highest price (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}low
|float
|Lowest price (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}volume
|float
|Volume (last 24H)

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}timestamp
|float (unix timestamp sec.msec)
|Unix timestamp

|===

[NOTE]
====
In case no ticker information exists for requested pair, an empty dictionary will be returned
====

.Examples

Example for *GET* _/exchanges/bittrex/tickers/BTC-1ST_

[source,json]
----
{
    "BTC-1ST":{
        "pair":"BTC-1ST",
        "last":0.00027,
        "priceChangePercent":5.4,
        "sell":0.00027,
        "buy":0.00026844,
        "high":0.00030997,
        "low":0.000251,
        "volume":1209270.05703722,
        "timestamp":1502369448.130
    }
}
----

Example for *GET* _/exchanges/bittrex/tickers/BTC-INVALID_

[source,json]
----
{
}
----
