= Trades

[NOTE]
====
Those routes require the feature _trades_ to be enabled for the requested exchange

[source,json]
----
{
    "features":{
        "trades":{
            "enabled":true
        }
    }
}
----

====

== Retrieves last trades for a given pair

*GET* _/exchanges/{exchangeId}/trades/{pair}_

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{pair}
|string
|Pair to retrieve last trades for (_X-Y_)

|===

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|afterTradeId
|integer
|
|Only retrieve trades with an _id_ > _afterTradeId_

|afterTimestamp
|float (unix timestamp sec.msec)
|
|Only retrieve trades with a _timestamp_ > _afterTimestamp_

|===

=== Result

Result will be an array of trade object (*the first one being the newest*)

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|id
|integer
|Unique identifier of the trade (will be null if not supported by exchange)

|quantity
|float
|Quantity bougth/sold during the trade

|rate
|float
|Per-unit price

|price
|float
|Total price (_quantity_ * _rate_)

|orderType
|string (_buy_,_sell_)
|Whether market maker was _buyer_ or _seller_

|timestamp
|float (unix timestamp sec.msec)
|Unix timestamp when trade was executed

|===

.Examples

Example for *GET* _/exchanges/{exchangeId}/trades/BTC-ETH_

[source,json]
----
[
    {
        "id":113538353,
        "quantity":0.14218557,
        "rate":0.07268002,
        "price":0.01033405,
        "orderType":"buy",
        "timestamp":1505727882.120
    },
    {
        "id":113538350,
        "quantity":20,
        "rate":0.07268002,
        "price":1.4536004,
        "orderType":"sell",
        "timestamp":1505727881.130
    },
    {
        "id":113538329,
        "quantity":1.46681041,
        "rate":0.07268002,
        "price":0.1066078,
        "orderType":"buy",
        "timestamp":1505727875.140
    }
]
----
