= History

[NOTE]
====
Those routes will only be available if _coinmarketcap_ service is enabled and if feature _history_ is enabled

They use Coin Market Cap https://coinmarketcap.com/currencies/{symbol}/historical-data/ and parse the html output (yeah, i'm _not proud_ of it)

====

== Retrieve history for a date range of a given symbol

*GET* _/coinmarketcap/history/{symbol}_

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{symbol}
|string
|Symbol to retrieve ticker for

|===

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|order
|string (_asc_,_desc_)
|desc
|If _desc_ newest entry will be first

|completeHistory
|boolean
|false
|If _true_ complete history will be retrieved

|to
|string (_yyyy-mm-dd_)
|_yesterday as yyyy-mm-dd_
|Date of the newest entry (will be ignored if _completeHistory_ is _true_)

|from
|string (_yyyy-mm-dd_)
|_to - 6 days_ as yyyy-mm-dd_
|Date of the oldest entry (will be ignored if _completeHistory_ is _true_)

|===

=== Result

Result will be an array of entries such as below

[NOTE]
====
If date is not available for part of the date range, there will be no entry with those dates in array. No error will be triggered
====

[cols="1a,1a,3a", options="header"]
|===
|Name
|Type
|Description

|date
|string (_yyyy-mm-dd_)
|Date of the entry

|open
|float
|Open price in _USD_

|close
|float
|Close price in _USD_

|high
|float
|Highest price (last 24H) in _USD_

|low
|float
|Lowest price (last 24H) in _USD_

|volume
|float
|Volume in _USD_

|market_cap
|float
|Market cap in _USD_

|===

.Examples

Example for *GET* _/coinmarketcap/history/NEO?to=2017-12-31_

[source,json]
----
[
    {
        "date":"2017-12-31",
        "open":72.5553,
        "high":78.0144,
        "low":67.6857,
        "close":75.9606,
        "volume":181357000,
        "market_cap":4716090000
    },
    {
        "date":"2017-12-30",
        "open":74.1821,
        "high":74.5422,
        "low":63.0207,
        "close":72.4032,
        "volume":202377000,
        "market_cap":4821840000
    },
    {
        "date":"2017-12-29",
        "open":65.7003,
        "high":74.8245,
        "low":63.1437,
        "close":73.9048,
        "volume":163331000,
        "market_cap":4270520000
    },
    {
        "date":"2017-12-28",
        "open":66.762,
        "high":66.9409,
        "low":58.2164,
        "close":65.4252,
        "volume":135592000,
        "market_cap":4339530000
    },
    {
        "date":"2017-12-27",
        "open":65.5263,
        "high":70.2858,
        "low":62.879,
        "close":66.8837,
        "volume":153715000,
        "market_cap":4259210000
    },
    {
        "date":"2017-12-26",
        "open":66.606,
        "high":68.7964,
        "low":61.8595,
        "close":65.5165,
        "volume":195466000,
        "market_cap":4329390000
    },
    {
        "date":"2017-12-25",
        "open":60.2677,
        "high":68.3742,
        "low":58.3853,
        "close":66.3243,
        "volume":170538000,
        "market_cap":3917400000
    }
]
----

== Retrieve history for a single date

*GET* _/coinmarketcap/history/{symbol}/{date}_

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{symbol}
|string
|Symbol to retrieve ticker for

|{date}
|string (_yyyy-mm-dd_)
|Date of the entry to retrieve

|===

=== Result

Result will be a single entry such as below

[cols="1a,1a,3a", options="header"]
|===
|Name
|Type
|Description

|date
|string (_yyyy-mm-dd_)
|Date of the entry

|open
|float
|Open price in _USD_

|close
|float
|Close price in _USD_

|high
|float
|Highest price (last 24H) in _USD_

|low
|float
|Lowest price (last 24H) in _USD_

|volume
|float
|Volume in _USD_

|market_cap
|float
|Market cap in _USD_

|===

.Examples

Example for *GET* _/coinmarketcap/history/NEO/2017-12-31_

[source,json]
----
{
    "date":"2017-12-31",
    "open":72.5553,
    "high":78.0144,
    "low":67.6857,
    "close":75.9606,
    "volume":181357000,
    "market_cap":4716090000
}
----

=== Result in case data does not exist

A _GatewayError.InvalidRequest.ObjectNotFound_ error will be returned

.Examples

Example for *GET* _/coinmarketcap/history/NEO/2000-01-01_

[source,json]
----
{
    "origin":"gateway",
    "error":"No data for this date",
    "route":{
        "method":"GET",
        "path":"/coinmarketcap/history/NEO/2000-01-01"
    },
    "extError":{
        "errorType":"GatewayError.InvalidRequest.ObjectNotFound",
        "message":"No data for this date",
        "data":{
            "date":"2000-01-01"
        }
    }
}
----
