#!/bin/bash
DOCKERFILE=Dockerfile
if [ "$DOCKER_TAG" == "dev" ]
then
    DOCKERFILE=Dockerfile.dev
elif [ "$DOCKER_TAG" == "rpi" ]
then
    DOCKERFILE=Dockerfile-rpi
elif [ "$DOCKER_TAG" == "rpi-dev" ]
then
    DOCKERFILE=Dockerfile-rpi.dev
fi
docker build -f $DOCKERFILE --force-rm=true --rm=true --build-arg CROSSBUILD=1 -t $IMAGE_NAME .
