#!/bin/bash
DOCKERFILE=Dockerfile
GIT_BRANCH=$SOURCE_BRANCH
if [ "$DOCKER_TAG" == "rpi-latest" ] || [ "$DOCKER_TAG" == "rpi-dev" ]
then
    DOCKERFILE=Dockerfile-rpi-crossbuild
fi
docker build -f $DOCKERFILE --force-rm=true --rm=true --build-arg GIT_BRANCH=$GIT_BRANCH -t $IMAGE_NAME .
