= Errors

REST API will return errors using an object with following format

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|origin
|string (_gateway,remote_)
|Origin of the error

* _gateway_ indicates error was generated by gateway (in case of invalid request for example)
* _remote_ indicates error was generated by _exchange_ or _service_ (authentication error for example)

|error
|string
|Error message

|route
|object
|The REST route for which the error was triggered

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}method
|string
|REST method

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}path
|string
|Request path

|extError
|object
|Extended information regarding the error

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}errorType
|string
|Error type (ex: _GatewayError.InvalidRequest.InvalidParameter_). See route *GET* _/server/errors_ for a complete list of possible errors

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}message
|string
|Error message

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}data
|object
|Content depends on the error type

|===

.Examples

Example for *GET* _/invalidRoute_ (invalid route)

[source,json]
----
{
    "origin":"gateway",
    "error":"Unknown route",
    "route":{
        "method":"GET",
        "path":"/invalidRoute"
    },
    "extError":{
        "errorType":"GatewayError.UnknownRoute",
        "message":"Unknown route",
        "data":{

        }
    }
}
----

Example for *GET* _/exchanges/binance/orderBooks/INVALID-PAIR_ (request rejected by exchange)

[source,json]
----
{
    "origin":"remote",
    "error":"Invalid symbol.",
    "route":{
        "method":"GET",
        "path":"/exchanges/binance/orderBooks/INVALID-PAIR"
    },
    "extError":{
        "errorType":"ExchangeError.InvalidRequest.UnknownError",
        "message":"Invalid symbol.",
        "data":{
            "exchange":"binance",
            "error":{
                "code":-1121,
                "msg":"Invalid symbol."
            }
        }
    }
}
----
