= Server

== Retrieve server uptime

*GET* _/server/uptime_

=== Result

Result will be a dictionary

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|uptime
|integer
|Uptime in seconds

|===

.Examples

Example for *GET* _/server/uptime_

[source,json]
----
{
    "uptime":"debug"
}
----

== Retrieve list of services and features

*GET* _/server/services_

=== Result

Result will be a dictionary with two entries :

* _exchanges_ : per-exchange features
* _others_ : features for other services such as _Push Over_

[NOTE]
====
* Only enabled exchanges will be present
* Value for a feature will always be an object _{"enabled":boolean}_
* When property _demo_ is _true_ for an entry, it means that this exchange or service is running in demo mode and will return *fake/random* data for API calls which require authentication (such as trading API on exchanges)
* When property _dummy_ is _true_ for an entry, it means that this exchange is a _dummy_ exchange (ie: _paper_ exchange used for testing purpose, it's unlikely you'll ever see this on your gateway instance)
====

.Examples

Example for *GET* _/server/services_

[source,json]
----
{
    "exchanges":{
        "binance":{
            "id":"binance",
            /* exchange type, it is possible to define multiple instance of one exchange */
            "type":"binance",
            "name":"Binance",
            "features":{
                "tickers":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving tickers for all pairs with a single request */
                    "allPairs":false
                },
                "wsTickers":{
                    "enabled":true
                },
                "orderBooks":{
                    "enabled":true
                },
                "wsOrderBooks":{
                    "enabled":true
                },
                "pairs":{
                    "enabled":true
                },
                "trades":{
                    "enabled":true
                },
                "wsTrades":{
                    "enabled":true
                },
                "klines":{
                    "enabled":true,
                    /* supported kline intervals */
                    "intervals":["1m","3m","5m","15m","30m","1h","2h","4h","6h","8h","12h","1d","3d","1w","1M"]
                },
                "wsKlines":{
                    "enabled":true,
                    /* supported kline intervals */
                    "intervals":["1m","3m","5m","15m","30m","1h","2h","4h","6h","8h","12h","1d","3d","1w","1M"]
                },
                "openOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving open orders for all pairs using a single request */
                    "allPairs":false
                },
                "closedOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving closed orders for all pairs using a single request */
                    "allPairs":false
                },
                "balances":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving balances for all pairs using a single request */
                    "allCurrencies":true
                }
            },
            "demo":false,
            "dummy":false,
            "feesPercent":0.1
        },
        "bittrex":{
            "id":"bittrex",
            /* exchange type, it is possible to define multiple instance of one exchange */
            "type":"bittrex",
            "name":"Bittrex",
            "features":{
                "tickers":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving tickers for all pairs with a single request */
                    "allPairs":true
                },
                "wsTickers":{
                    "enabled":true
                },
                "orderBooks":{
                    "enabled":true
                },
                "wsOrderBooks":{
                    "enabled":true
                },
                "pairs":{
                    "enabled":true
                },
                "trades":{
                    "enabled":true
                },
                "wsTrades":{
                    "enabled":true
                },
                "klines":{
                    "enabled":false
                },
                "wsKlines":{
                    "enabled":false
                },
                "openOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving open orders for all pairs using a single request */
                    "allPairs":true
                },
                "closedOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving closed orders for all pairs using a single request */
                    "allPairs":true
                },
                "balances":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving balances for all pairs using a single request */
                    "allCurrencies":true
                }
            },
            "demo":false,
            "dummy":false,
            "feesPercent":0.25
        },
        "poloniex":{
            "id":"poloniex",
            /* exchange type, it is possible to define multiple instance of one exchange */
            "type":"poloniex",
            "name":"Poloniex",
            "features":{
                "tickers":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving tickers for all pairs with a single request */
                    "allPairs":true
                },
                "wsTickers":{
                    "enabled":true
                },
                "orderBooks":{
                    "enabled":true
                },
                "wsOrderBooks":{
                    "enabled":true
                },
                "pairs":{
                    "enabled":true
                },
                "trades":{
                    "enabled":true
                },
                "wsTrades":{
                    "enabled":true
                },
                "klines":{
                    "enabled":false
                },
                "wsKlines":{
                    "enabled":false
                },
                "openOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving open orders for all pairs using a single request */
                    "allPairs":true
                },
                "closedOrders":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving closed orders for all pairs using a single request */
                    "allPairs":true
                },
                "balances":{
                    "enabled":true,
                    /* whether or not exchange supports retrieving balances for all pairs using a single request */
                    "allCurrencies":true
                }
            },
            "demo":false,
            "dummy":false,
            "feesPercent":0.25
        }
    },
    "others":{
        "coinmarketcap":{
            "id":"coinmarketcap",
            "name":"Coin Market Cap",
            "features":{

            },
            "demo":false
        },
        "pushover":{
            "id":"pushover",
            "name":"Push Over",
            "features":{

            },
            "demo":false
        }
    }
}
----

== Retrieve statistics of exchanges API (success, failure)

*GET* _/server/statistics_

=== Result

Result will be a dictionary with two entries :

* _exchanges_ : per-exchange statistics
* _others_ : statistics for other services such as _Push Over_

[NOTE]
====
* Statistics will only be created the first time an API is called (ie: statistics for _getTickers_ API of an exchange won't appear if it has not be called yet)
====

.Examples

Example for *GET* _/server/statistics_

[source,json]
----
{
    "exchanges":{
        "fakeExchange":{
            "getBalances":{
                "success":2,
                "failure":0
            }
        },
        "poloniex":{
            "getPairs":{
                "success":3,
                "failure":0
            },
            "getOrderBooks":{
                "success":1,
                "failure":0
            },
            "getTrades":{
                "success":1,
                "failure":0
            },
            "getTickers":{
                "success":2,
                "failure":0
            }
        }
    },
    "others":{
    }
}
----
