= Order books

== Retrieve order book for a given pair

*GET* _/exchanges/bittrex/orderBooks/{pair}_

Uses Bittrex _getorderbook_ API

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{pair}
|string
|Pair to retrieve order book for (_X-Y_)

|===

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|outputFormat
|string (_custom_,_exchange_)
|custom
|If value is _exchange_ result returned by remote exchange will be returned untouched

|===

=== Result

[NOTE]
====
This only applies when _outputFormat_ is set to _custom_
====

Result will be a dictionary containing _buy_ and _sell_ entries in the order book

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|buy
|object[]
|List of _bid_ entries in the order book

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}rate
|float
|Buy rate

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}quantity
|float
|Quantity requested

|sell
|object[]
|List of _ask_ entries in the order book

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}rate
|float
|Sell rate

|{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}quantity
|float
|Quantity offered

|===

.Examples

Example for *GET* _/exchanges/bittrex/orderBooks/USDT-ETH_

[source,json]
----
{
    "buy":[
        {
            "rate":298.10023952,
            "quantity":3.00278376
        },
        {
            "rate":298.10023948,
            "quantity":1.5
        },
        ...
    ],
    "sell":[
        {
            "rate":298.77999986,
            "quantity":0.9235867
        },
        {
            "rate":298.77999987,
            "quantity":19.521
        },
        {
            "rate":298.77999988,
            "quantity":1.50716556
        },
        ...
    ]
}
----
