= Trades

== Retrieves last trades for a given pair

*GET* _/exchanges/bittrex/trades/{pair}_

Uses Bittrex _getmarkethistory_ API

=== Url parameters

[cols="1,1a,3a", options="header"]
|===

|Name
|Type
|Description

|{pair}
|string
|Pair to retrieve last trades for (_X-Y_)

|===

=== Optional query parameters

[cols="1,1a,1a,3a", options="header"]
|===

|Name
|Type
|Default
|Description

|outputFormat
|string (_custom_,_exchange_)
|custom
|If value is _exchange_ result returned by remote exchange will be returned untouched

|afterTradeId
|integer
|
|Only retrieve trades with an _id_ > _afterTradeId_ (will be ignored if _outputFormat_ is set to _exchange_)

|===

[NOTE]
====
Bittrex only allows to retrieve a maximum of 200 trades at once
====

=== Result

[NOTE]
====
This only applies when _outputFormat_ is set to _custom_
====

Result will be an array of trade object (*the first one being the newest*)

[cols="1,1a,3a", options="header"]
|===
|Name
|Type
|Description

|id
|integer
|Unique identifier of the trade

|quantity
|float
|Quantity bougth/sold during the trade

|rate
|float
|Per-unit price

|price
|float
|Total price (_quantity_ * _rate_)

|timestamp
|integer (unix timestamp)
|Unix timestamp when trade was executed

|===

.Examples

Example for *GET* _/exchanges/bittrex/trades/USDT-ETH_

[source,json]
----
[
    {
        "id":113538353,
        "quantity":0.14218557,
        "rate":0.07268002,
        "price":0.01033405,
        "timestamp":1505727882
    },
    {
        "id":113538350,
        "quantity":20,
        "rate":0.07268002,
        "price":1.4536004,
        "timestamp":1505727881
    },
    {
        "id":113538329,
        "quantity":1.46681041,
        "rate":0.07268002,
        "price":0.1066078,
        "timestamp":1505727875
    },
    {
        "id":113538323,
        "quantity":0.4037842,
        "rate":0.07268002,
        "price":0.02934704,
        "timestamp":1505727872
    },
    {
        "id":113538313,
        "quantity":77.7,
        "rate":0.07268002,
        "price":5.64723755,
        "timestamp":1505727869
    },
    {
        "id":113538308,
        "quantity":72.96,
        "rate":0.07268002,
        "price":5.30273425,
        "timestamp":1505727867
    },
    {
        "id":113538307,
        "quantity":0.025,
        "rate":0.07269144,
        "price":0.00181728,
        "timestamp":1505727867
    },
    {
        "id":113538306,
        "quantity":6,
        "rate":0.0727,
        "price":0.4362,
        "timestamp":1505727867
    }
]
----
